name: Build and Package

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install zstandard brotli pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: compressed-files-exe
        path: dist/main.exe
